Repository Ama-Get-Don/Ama-Get-Don, pull requests merged in 2024-08, with the labels that each got.

#41 sign_up_complete ui
  tookie/src/images/seed.png
  tookie/src/images/sprout.png
  tookie/src/images/tookie.png
  tookie/src/pages/signup/SignUpComplete.tsx
Labels: enhancement

#59 Feature/backend chat
  .gitignore
  tookie-BE/chat/Multi_Turn/core_Store.py
  tookie-BE/chat/Prompt/keyword_extract.py
  tookie-BE/chat/Prompt/question_extract.py
  tookie-BE/chat/Prompt/seed.py
  tookie-BE/chat/Prompt/sprout.py
  tookie-BE/chat/Prompt/tookie.py
  tookie-BE/chat/RAG/core_Rag.py
  tookie-BE/chat/chain/__init__.py
  tookie-BE/chat/chain/core_Chain.py
  tookie-BE/chat/chain/core_Chain_mock.py
  tookie-BE/chat/chat_router.py
  tookie-BE/chat/dto/user_Message.py
  tookie-BE/models.py
Labels: bug, enhancement

#62 [feat] async base chat_router
  tookie-BE/chat/Prompt/keyword_extract.py
  tookie-BE/chat/Prompt/question_extract.py
  tookie-BE/chat/Prompt/seed.py
  tookie-BE/chat/Prompt/sprout.py
  tookie-BE/chat/Prompt/tookie.py
  tookie-BE/chat/RAG/core_Rag.py
  tookie-BE/chat/chain/core_Chain.py
  tookie-BE/chat/chain/core_Chain_mock.py
  tookie-BE/chat/chat_router.py
  tookie-BE/models.py
Labels: enhancement

#71 Feat/backend chat
  .gitignore
  alembic/README
  alembic/env.py
  alembic/script.py.mako
  tookie-BE/app.py
  tookie-BE/chat/Chain/__init__.py
  tookie-BE/chat/Chain/core_Chain.py
  tookie-BE/chat/Chain/core_Chain_mock.py
  tookie-BE/chat/Prompt/company_extract.py
  tookie-BE/chat/Prompt/question_extract.py
  tookie-BE/chat/Prompt/seed.py
  tookie-BE/chat/Prompt/sprout.py
  tookie-BE/chat/Prompt/tookie.py
  tookie-BE/chat/chain/core_Chain.py
  tookie-BE/chat/chat_router.py
  tookie-BE/models.py
  tookie-BE/user/user_crud.py
  tookie-BE/user/user_router.py
  tookie-BE/user/user_schema.py
Labels: bug, enhancement

#83 Feat/backend chat
  tookie-BE/chat/chat_crud.py
  tookie-BE/chat/chat_router.py
  tookie-BE/user/user_router.py
  tookie-BE/user/user_schema.py
Labels: enhancement

#115 Feat/backend chat
  tookie-BE/chat/Chain/core_Chain.py
  tookie-BE/chat/Prompt/seed.py
  tookie-BE/chat/Prompt/sprout.py
  tookie-BE/chat/chat_crud.py
  tookie-BE/chat/chat_router.py
  tookie-BE/dockerfile
  tookie-BE/requirements.txt
  tookie-BE/user/user_router.py
  tookie-BE/user/user_schema.py
Labels: enhancement

#116 [fix] docker-file
  tookie-BE/dockerfile
Labels: bug, enhancement

#120 [docs] readme
  README.md
Labels: documentation

#121 [docs] readme
  README.md
Labels: documentation

#122 [docs] readme
  README.md
  readme_images/team.png
Labels: documentation

#123 [docs] readme
  README.md
  readme_images/team.png
Labels: documentation
